create table public.card_sets (
  id bigint generated by default as identity primary key,
  tcg_slug text not null,
  slug text not null unique,
  name text not null,
  status text not null default 'draft' check (status in ('draft', 'live', 'archived')),
  release_date date,
  serials_per_card integer not null default 200 check (serials_per_card > 0),
  created_at timestamptz not null default now()
);

alter table public.card_sets enable row level security;

revoke all on table public.card_sets from anon, authenticated;
grant select on table public.card_sets to anon, authenticated;

create policy "Public can view live card sets"
on public.card_sets for select to anon
using (status = 'live');

create policy "Admins can view all card sets"
on public.card_sets for select to authenticated
using (
  status = 'live'
  or (
    (select auth.jwt() ->> 'aal') = 'aal2'
    and exists (
      select 1 from public.admins
      where admins.user_id = (select auth.uid())
    )
  )
);

insert into public.card_sets (tcg_slug, slug, name, status, release_date)
values
  ('yugioh', 'magnificent-monsters', 'Magnificent Monsters', 'live', '2026-09-03'),
  ('yugioh', 'magnificent-maestros', 'Magnificent Maestros', 'draft', '2026-11-12');

alter table public.cards add column set_id bigint references public.card_sets(id);

update public.cards
set set_id = (select id from public.card_sets where slug = 'magnificent-monsters')
where set_id is null;

alter table public.cards alter column set_id set not null;
alter table public.cards add constraint cards_set_id_name_key unique (set_id, name);
create index cards_set_id_idx on public.cards (set_id);

with maestro_cards(name, image_url, position) as (
  values
    ('Blue-Eyes White Dragon, the White Phantom Beast', 'https://images.ygoprodeck.com/images/cards_cropped/30397786.jpg', 1),
    ('Deep-Eyes White Dragon, the Blue Abyss', 'https://images.ygoprodeck.com/images/cards_cropped/67886895.jpg', 2),
    ('The Guiding Flute of Summoning Dragons', 'https://images.ygoprodeck.com/images/cards_cropped/93871599.jpg', 3),
    ('Cyber End Dragon, the Final Strike Dragon', 'https://images.ygoprodeck.com/images/cards_cropped/30275298.jpg', 4),
    ('Cyber Dragon, the Luminous Mech Dragon', 'https://images.ygoprodeck.com/images/cards_cropped/66664203.jpg', 5),
    ('Future Fusion Nova', 'https://images.ygoprodeck.com/images/cards_cropped/92058902.jpg', 6),
    ('Crimson Dragon Quetzalcoatl', 'https://images.ygoprodeck.com/images/cards_cropped/29053656.jpg', 7),
    ('Red Nova Dragon - Burning Soul', 'https://images.ygoprodeck.com/images/cards_cropped/65541655.jpg', 8),
    ('Red Dragon Archfiend''s Chains', 'https://images.ygoprodeck.com/images/cards_cropped/92936364.jpg', 9),
    ('Neo Galaxy-Eyes Photon Dragon - Photon Howling', 'https://images.ygoprodeck.com/images/cards_cropped/28331069.jpg', 10),
    ('Galaxy-Eyes Photon Change Dragon', 'https://images.ygoprodeck.com/images/cards_cropped/54725177.jpg', 11),
    ('Galaxy Defense Robot Orbital 7', 'https://images.ygoprodeck.com/images/cards_cropped/91714772.jpg', 12),
    ('Starving Venom Fusion Dragon of the Four Heavenly Dragons', 'https://images.ygoprodeck.com/images/cards_cropped/27118421.jpg', 13),
    ('Clear Wing Synchro Dragon of the Four Heavenly Dragons', 'https://images.ygoprodeck.com/images/cards_cropped/54603525.jpg', 14),
    ('Dark Rebellion Xyz Dragon of the Four Heavenly Dragons', 'https://images.ygoprodeck.com/images/cards_cropped/90091224.jpg', 15),
    ('Borreload Liberator Dragon', 'https://images.ygoprodeck.com/images/cards_cropped/27096833.jpg', 16),
    ('Rokket Barrage', 'https://images.ygoprodeck.com/images/cards_cropped/53481938.jpg', 17),
    ('Triple Borrel Launch', 'https://images.ygoprodeck.com/images/cards_cropped/89875646.jpg', 18)
), next_card_id as (
  select coalesce(max(id), 0) as value from public.cards
)
insert into public.cards (id, name, image_url, set_id)
select next_card_id.value + maestro_cards.position,
       maestro_cards.name,
       maestro_cards.image_url,
       card_sets.id
from maestro_cards
cross join next_card_id
cross join public.card_sets
where card_sets.slug = 'magnificent-maestros';

with new_serials as (
  select cards.id as card_id,
         numbers.serial_number,
         regions.region,
         row_number() over (order by cards.id, regions.region, numbers.serial_number) as position
  from public.cards
  join public.card_sets on card_sets.id = cards.set_id
  cross join generate_series(1, 100) as numbers(serial_number)
  cross join (values ('AMERICAS'::text), ('E'::text)) as regions(region)
  where card_sets.slug = 'magnificent-maestros'
), next_serial_id as (
  select coalesce(max(id), 0) as value from public.serials
)
insert into public.serials (id, card_id, serial_number, region, status)
select next_serial_id.value + new_serials.position,
       new_serials.card_id,
       new_serials.serial_number,
       new_serials.region,
       'unreported'
from new_serials
cross join next_serial_id;

drop policy if exists "Public can view cards" on public.cards;
drop policy if exists "Authenticated users can view cards" on public.cards;

create policy "Public can view cards in live sets"
on public.cards for select to anon
using (
  exists (
    select 1 from public.card_sets
    where card_sets.id = cards.set_id and card_sets.status = 'live'
  )
);

create policy "Authenticated users can view live cards or admin drafts"
on public.cards for select to authenticated
using (
  exists (
    select 1 from public.card_sets
    where card_sets.id = cards.set_id and card_sets.status = 'live'
  )
  or (
    (select auth.jwt() ->> 'aal') = 'aal2'
    and exists (
      select 1 from public.admins
      where admins.user_id = (select auth.uid())
    )
  )
);

drop policy if exists "Public can view serials" on public.serials;
drop policy if exists "Authenticated users can view serials" on public.serials;

create policy "Public can view serials in live sets"
on public.serials for select to anon
using (
  exists (
    select 1
    from public.cards
    join public.card_sets on card_sets.id = cards.set_id
    where cards.id = serials.card_id and card_sets.status = 'live'
  )
);

create policy "Authenticated users can view live serials or admin drafts"
on public.serials for select to authenticated
using (
  exists (
    select 1
    from public.cards
    join public.card_sets on card_sets.id = cards.set_id
    where cards.id = serials.card_id and card_sets.status = 'live'
  )
  or (
    (select auth.jwt() ->> 'aal') = 'aal2'
    and exists (
      select 1 from public.admins
      where admins.user_id = (select auth.uid())
    )
  )
);

create or replace function public.submit_pull(
  p_serial_id bigint,
  p_photo_url text,
  p_country text default null,
  p_source_url text default null,
  p_notes text default null,
  p_submitter_email text default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_submission_id bigint;
  v_serial_status text;
  v_set_status text;
  v_country text := nullif(btrim(p_country), '');
  v_source_url text := nullif(btrim(p_source_url), '');
  v_notes text := nullif(btrim(p_notes), '');
  v_email text := nullif(lower(btrim(p_submitter_email)), '');
begin
  select serials.status, card_sets.status
  into v_serial_status, v_set_status
  from public.serials
  join public.cards on cards.id = serials.card_id
  join public.card_sets on card_sets.id = cards.set_id
  where serials.id = p_serial_id;

  if v_serial_status is null then
    raise exception 'Serial not found';
  end if;

  if v_set_status <> 'live' then
    raise exception 'This set is not open for submissions yet';
  end if;

  if p_photo_url is null
     or p_photo_url !~ '^submissions/[A-Za-z0-9._-]+$'
     or not exists (
       select 1 from storage.objects
       where bucket_id = 'submission-evidence' and name = p_photo_url
     ) then
    raise exception 'Valid uploaded photo evidence is required';
  end if;

  if v_country is not null and char_length(v_country) > 100 then
    raise exception 'Country is too long';
  end if;

  if v_source_url is not null and (char_length(v_source_url) > 2048 or v_source_url !~* '^https?://') then
    raise exception 'Source link must be a valid HTTP or HTTPS URL';
  end if;

  if v_notes is not null and char_length(v_notes) > 5000 then
    raise exception 'Notes are too long';
  end if;

  if v_email is not null and (
    char_length(v_email) > 320
    or v_email !~* '^[A-Z0-9.!#$%&''*+/=?^_`{|}~-]+@[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?(?:\.[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?)+$'
  ) then
    raise exception 'Email address is invalid';
  end if;

  if v_serial_status = 'confirmed' and v_email is null then
    raise exception 'Email is required when challenging a confirmed serial';
  end if;

  insert into public.submissions (serial_id, photo_url, country, source_url, notes, submitter_email, status)
  values (p_serial_id, p_photo_url, v_country, v_source_url, v_notes, v_email, 'pending')
  returning id into v_submission_id;

  return v_submission_id;
end;
$$;
