create table public.discovery_runs (
  id bigint generated by default as identity primary key,
  started_by uuid not null references auth.users(id),
  status text not null default 'running' check (status in ('running', 'completed', 'failed')),
  cards_searched integer not null default 0 check (cards_searched >= 0),
  results_found integer not null default 0 check (results_found >= 0),
  error_message text,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create table public.pull_discoveries (
  id bigint generated by default as identity primary key,
  run_id bigint not null references public.discovery_runs(id) on delete cascade,
  card_id bigint not null references public.cards(id),
  source_url text not null,
  source_domain text not null,
  source_title text not null,
  search_summary text,
  detected_serial text,
  confidence integer not null default 50 check (confidence between 0 and 100),
  status text not null default 'candidate' check (status in ('candidate', 'investigating', 'rejected', 'promoted')),
  found_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id),
  unique (card_id, source_url)
);

create index pull_discoveries_status_found_idx
  on public.pull_discoveries (status, found_at desc);

alter table public.discovery_runs enable row level security;
alter table public.pull_discoveries enable row level security;

revoke all on public.discovery_runs from anon, authenticated;
revoke all on public.pull_discoveries from anon, authenticated;
grant select on public.discovery_runs to authenticated;
grant select, update on public.pull_discoveries to authenticated;

create policy "Owners can view discovery runs"
on public.discovery_runs for select to authenticated
using (
  (select auth.jwt() ->> 'aal') = 'aal2'
  and exists (
    select 1 from public.admins
    where admins.user_id = (select auth.uid()) and admins.is_owner = true
  )
);

create policy "Owners can view discoveries"
on public.pull_discoveries for select to authenticated
using (
  (select auth.jwt() ->> 'aal') = 'aal2'
  and exists (
    select 1 from public.admins
    where admins.user_id = (select auth.uid()) and admins.is_owner = true
  )
);

create policy "Owners can update discoveries"
on public.pull_discoveries for update to authenticated
using (
  (select auth.jwt() ->> 'aal') = 'aal2'
  and exists (
    select 1 from public.admins
    where admins.user_id = (select auth.uid()) and admins.is_owner = true
  )
)
with check (
  (select auth.jwt() ->> 'aal') = 'aal2'
  and exists (
    select 1 from public.admins
    where admins.user_id = (select auth.uid()) and admins.is_owner = true
  )
);
